### ISSUE TITLE
Maps apk 10.18.0 to 10.35.2

### ISSUE THREAD

**Issue by lf111** [android-police/apkmirror-public#123]
#### Expected behavior
After installation, I expected Menu in French, as usual, because it's my default langage

#### Actual behavior
All the menu are in English. It seems all these apk of Maps are not able to be in french. When I come back to Maps 9.56, it's in French.
So it seem that I can't find a french version of google Maps in 10.18 to 10.32.
The latest versions are too slow on my old phone (Samsung galaxy S4 mini).
Do you confirm, or do you think there's a way to find a french version (of course, I don't speak about the Navigation Voice, but about the app itself (Menu, etc)
Thanks a lot

**Comment by archon810** [comment]
Google has moved to split apks for Maps a long time ago, though for some reason they only split off languages and not architectures or DPIs. Makes no sense.

The solution is to install the versions marked as bundles using Apkmirror Installer. For example, https://www.apkmirror.com/apk/google-inc/maps/maps-10-36-5-release/google-maps-navigate-explore-10-36-5-4-android-apk-download/.

Since we only recently rolled out split apk support, only the recent versions of Maps have bundles with languages.
