### ISSUE TITLE
Duplicate APKs of PUBG MOBILE - RUNIC POWER 1.2.0

### ISSUE THREAD

**Issue by andyg21** [android-police/apkmirror-public#172]
#### Expected behavior
Unique APK pages per variant

#### Actual behavior
Duplicate APK pages for same variants:
1)
https://www.apkmirror.com/apk/tencent-games/pubgmobile/pubgmobile-1-2-0-release/pubg-mobile-frost-festival-1-2-0-2-android-apk-download/
https://www.apkmirror.com/apk/tencent-games/pubgmobile/pubgmobile-1-2-0-release/pubg-mobile-runic-power-1-2-0-3-android-apk-download/
2)
https://www.apkmirror.com/apk/tencent-games/pubgmobile/pubgmobile-1-2-0-release/pubg-mobile-frost-festival-1-2-0-android-apk-download/
https://www.apkmirror.com/apk/tencent-games/pubgmobile/pubgmobile-1-2-0-release/pubg-mobile-runic-power-1-2-0-2-android-apk-download/

#### Steps to reproduce the problem
Visit the links give as above.

**Comment by archon810** [comment]
Yeah... I noticed this as well. The reason is annoying and complicated, but here goes.

Google for some reason sometimes has 2 versions of an APK which varies in some super minimal way that doesn't even show up upon unzipping. When that started happening, we started treating APKs with the same set of architectures, DPIs, etc. as similar and only allowing one of them. It's really annoying because we can't determine if it'll be a similar APK before the upload finishes, and it wastes bandwidth for everyone. We do have an optimization cache that remembers MD5 hashes for similar APKs and if the MD5 matches before the upload, the user is immediately notified that their APK is similar.

Anyway, in the case of PUBG, they also distribute another APK that has the obb inside but is otherwise the same. This is why I turned off the "block similar APKs" setting for this app and was able to upload it here https://www.apkmirror.com/apk/tencent-games/pubgmobile/pubgmobile-1-2-0-release/pubg-mobile-runic-power-1-2-0-android-apk-download/. Unfortunately, this had the side effect of allowing those 2 dupe APKs.

I've now deleted them to avoid confusion and re-enabled the "block similar APKs" setting. I guess I'll just temporarily disable it in the future long enough to upload the APK with the obb and then enable it again.

**Comment by andyg21** [comment]
Ok, BTW, You can prevent this by comparing file MD5 also.

**Comment by archon810** [comment]
Which file MD5s? The APKs? As I explained, the files actually differ in really minor ways. The MD5s are different between similar apks.

**Comment by andyg21** [comment]
Ok, no issues. But both pages had shown same MD5s when I checked.

**Comment by archon810** [comment]
They were definitely different. You may have looked at the certificate MD5, which isn't the correct value to examine.
