### ISSUE TITLE
cannot download apk's

### ISSUE THREAD

**Issue by Astoreth** [android-police/apkmirror-public#49]
#### Expected behavior
Clicking on the download link should start downloading the apk requested. 

#### Actual behavior
Clicking on the download link reloads the page. This happens on my android device (where I use Firefox) as well as on my desktop (where I use Waterfox). I tried disabling all my 'privacy'-addons such as ublock origin and decentraleyes, I disconnected my vpn and accepted all cookies, but the problem persists. The interesting part is that this did not happen before, I succesfully downloaded several apk's from this site yesterday as well as today, but all of a sudden this did not work anymore, without me changing anything to my settings or anything. Nevertheless I guess it does have something to do with my settings, but I cannot figure out which ones. Anyone here any clue about what my problem may be? As said it worked in the past, and I can still download apk's from other sites, such as apkpure.

#### Steps to reproduce the problem
Just try to download any apk, I tried several, and also several versions of one app.

**Comment by archon810** [comment]
The only thing I can think of is your privacy add-ons somehow tripped our anti-hotlinking logic, which redirects to a page hosting the apk, and Cloudflare cached the response in your geographic location, but it shouldn't happen since we use no-cache headers on such redirects.

Otherwise, I'm really not sure, especially when it's happening to all APKs as you're saying. Is it possible your HTTP referer is getting mangled (not stripped, but actually rewritten to be something other than apkmirror.com)?

Can you look at the response headers for the download request and post them here? It's not happening to anyone else that I know of.

**Comment by archon810** [comment]
No response has been received. Closing.

**Comment by temporaryrespite** [comment]
"Download APK" acts like a page refresh instead.

#### Expected behavior
See the download page which also attempts to auto-download the APK.

#### Actual behavior
pressing "Download APK" just simply refreshes the webpage as if I pressed Reload button in browser.



#### Steps to reproduce the problem
1. On ArchLinux, in Firefox 75.0a1 (2020-03-02) (64-bit) (but not the upstream version), load either of these two pages:
A. https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-20-06-16-release/google-play-services-20-06-16-000300-296104215-android-apk-download/
B. https://www.apkmirror.com/apk/nick-nack-development/dpi-checker/dpi-checker-6-0-release/dpi-checker-6-0-2-android-apk-download/
2. click "Download APK"


#### Other info
There's a warning in Ctrl+Shit+J (in firefox) aka `Multiprocess Browser Console`:
`Content Security Policy: Couldn’t process unknown directive ‘prefetch-src’`
No red errors.

This worked as expected only once(and thus was able to download one of the APKs), and only after I've allowed requests(via uMatrix addon) to the hostname `instant.page`. Now they are still allowed, however it acts the same: it just refreshes the page. Weird as I haven't changed anything since then, trying to redownload the same APK which once worked, but still getting page refresh instead.

I haven't tried without any addons, or with a clean firefox profile, or with upstream archlinux firefox. Because, since it worked once, the problem must not be on my side?!

> Can you look at the response headers for the download request and post them here?

Response headers you say? The `Network` tab inside the F12 miniframe that firefox opens is white/blank even if I do a shift+refresh.

**Comment by archon810** [comment]
I was just able to successfully download the APKs:
![image](https://user-images.githubusercontent.com/469543/76153443-e6a6e880-6080-11ea-8d95-0d2cb2d4d49c.png)

This issue does come up sometimes, but we haven't been able to trace its origins.

I don't use Firefox dev tools, but if you use Chrome, can you:

1. Open Dev Tools and go to the Network tab.
1. Enable "Preserve log" there.
1. Visit the page that's giving you trouble, such as https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-20-06-16-release/google-play-services-20-06-16-000300-296104215-android-apk-download/download/, filter by "download.php" and paste the response headers?

For example:
![image](https://user-images.githubusercontent.com/469543/76153498-b27ff780-6081-11ea-8cf6-d20ff1fce07e.png)

**Comment by temporaryrespite** [comment]
[It](https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-20-06-16-release/google-play-services-20-06-16-000304-296104215-android-apk-download/) seems to always work in Chromium, and (almost)never work in Firefox. (I say _almost_ because I did make it work once, as mentioned)
Due to some Firefox [bug](https://github.com/android-police/apkmirror-public/issues/49#issuecomment-596136667), I'm unable to see the network requests, however I tried mozregression and can't find a version which doesn't have tabcrash on startup, weird. Oh wait, I found one:  mozilla-central build for 2020-03-10  and it seems to work just like chromium.
Then I can only assume it's the vendor.js settings that I've set. Or something like that.
I guess this can be closed then?
