### ISSUE TITLE
[Feature Request] Adapt new Play Store app icon rules

### ISSUE THREAD

**Issue by Stanzilla** [android-police/apkmirror-public#92]
In the light of https://www.androidpolice.com/2019/03/15/new-play-store-app-icon-rules-include-squircle-mandate-no-more-transparent-backgrounds/ it would be nice if APKM would do the same. Would also help with https://github.com/android-police/apkmirror-public/issues/86

**Comment by archon810** [comment]
We will use whatever icons developers provide in their apps and we will fall back to the web Play Store otherwise.

There's no easy way for us that we figured out to even get true XML-based adaptive icons out of APKs, so we rely on extracting images and processing web Play Store icons as a fallback.
